In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

## Tensors

In [8]:
a = np.zeros(shape=(3,4))
print(a.dtype, type(a))
print(a)

float64 <class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
b = torch.zeros(3,4,dtype=torch.long)
print(b.dtype, type(b) )
print(b)

torch.int64 <class 'torch.Tensor'>
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [11]:
c = torch.tensor(a)
print(c.dtype, type(c))
print(c)

torch.float64 <class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


## operations

In [14]:
print(torch.add(c, b))
print(b + c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [15]:
res = torch.empty(3,4)
torch.add(b,c,out=res)
res

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## resize

In [17]:
b.reshape(4,3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [18]:
b.view(4,3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [19]:
b.view(-1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## converting tensor to np array

In [20]:
b.numpy()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## moving tensor to gpu

In [22]:
b.cuda()

In [ ]:
b.to('cuda:0')

## using torch autograd

In [36]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [37]:
y = x + 2

In [38]:
y.grad_fn

In [39]:
z = y.mean()
z

tensor(3., grad_fn=<MeanBackward0>)

In [40]:
z.backward()

In [41]:
print(x.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


## going back to np array

In [42]:
x.numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [43]:
x.detach().numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)