## Pytorch api
https://pytorch.org/docs/stable/torch.html

In [44]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from torch.autograd import Variable

## Tensors

In [45]:
a = np.zeros(shape=(3,4))
print(a.dtype, type(a))
print(a)

float64 <class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [46]:
b = torch.zeros(3,4,dtype=torch.long)
print(b.dtype, type(b) )
print(b)

torch.int64 <class 'torch.Tensor'>
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [47]:
c = torch.tensor(a)
print(c.dtype, type(c))
print(c)

torch.float64 <class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


## operations

In [48]:
print(torch.add(c, b))
print(b + c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [50]:
res = torch.empty(3,4)
torch.add(b,c,out=res)
res

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## resize

In [51]:
b.reshape(4,3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [53]:
b.view(4,3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [55]:
b.view(-1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## converting tensor to np array

In [56]:
b.numpy()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## moving tensor to gpu

In [59]:
b.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [60]:
b.device

device(type='cpu')

In [14]:
b.to('cuda:0')

## using torch autograd

In [61]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [63]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [64]:
y.grad_fn

In [65]:
z = y.mean()
z

tensor(3., grad_fn=<MeanBackward0>)

In [66]:
z.backward()

In [67]:
print(x.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [69]:
x = x - 0.001 * x.grad

In [70]:
x

tensor([[0.9998, 0.9998],
        [0.9998, 0.9998]], grad_fn=<SubBackward0>)

In [72]:
X = Variable(torch.ones(2, 2), requires_grad=True)
X

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

## going back to np array

In [73]:
x.numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [74]:
x.detach().numpy()

array([[0.99975, 0.99975],
       [0.99975, 0.99975]], dtype=float32)

## tensor multiplication

In [75]:
a = torch.randn(3,4)
b = torch.randn(3,)
c = torch.matmul(b,a)
c, b@a

(tensor([-0.7212, -0.3108,  0.2029, -0.9934]),
 tensor([-0.7212, -0.3108,  0.2029, -0.9934]))

In [76]:
b = torch.randn(3,4)
a*b

tensor([[ 0.0863,  0.9711,  1.2593, -0.0984],
        [-2.2841,  0.3035,  0.6223, -0.5677],
        [ 1.8014, -0.8375, -1.4628, -0.9615]])

## manipulating tensor data

In [77]:
print(b)
b.data.fill_(2.)
b

tensor([[-1.0785, -2.2144, -0.6867, -0.1268],
        [-2.0290,  0.4895, -1.3142, -0.9297],
        [-1.2368,  0.7786,  0.8858,  0.9369]])


tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])